name: Build and test

on:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - '!.github/workflows/build-and-test.yml'
      - .vscode/**
      - images/**
  pull_request:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - '!.github/workflows/build-and-test.yml'
      - .vscode/**
      - images/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & test w/zig
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['master']

    steps:
      - uses: actions/checkout@v4

      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.version }}

      - name: Lint
        run: zig fmt --check .

      - name: Build and test
        run: zig build test

      - name: Install kcov
        run: |
          sudo apt-get update
          sudo apt-get install -y kcov

      - name: Generate coverage reports
        run: kcov $PWD/coverage ./zig-cache/o/*/test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          verbose: true
